name: yummy_mobile
description: A delivery service food order for customers.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  animator: ^3.3.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.1.0
  lottie: ^2.5.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:

    - assets/images/splash/pancake_berry_1.jpg
    - assets/images/splash/cake_berry.jpg
    - assets/images/splash/pancake_berry.jpg
    - assets/images/splash/sandwish.jpg
    - assets/images/splash/spaghetti.jpg
    - assets/images/splash/strawberry.jpg
    - assets/images/product_icon/logo_main.png
    - assets/images/product_icon/logo_sub.png
    - assets/images/product_icon/logo_medium.png
    - assets/images/social_media/facebook.png
    - assets/images/social_media/gmail.png
    - assets/images/social_media/instagram.png
    - assets/icons/animation_lkjzljaq.json
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
