name: yummy_mobile
description: A delivery service food order for customers. 


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
  
    - assets/images/pancake_berry_1.jpg
    - assets/images/cake_berry.jpg
    - assets/images/pancake_berry.jpg
    - assets/images/sandwish.jpg
    - assets/images/spaghetti.jpg
    - assets/images/strawberry.jpg
    - assets/images/logo.png


 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
